### ISSUE TITLE
changes to copter binary names

### ISSUE THREAD

**Issue by tridge** [ArduPilot/apm_planner#1001]
Hi Bill,
This is a heads up that binary names for copter builds are changing, which will affect firmware upload
I've created a MP issue describing it here:
https://github.com/ArduPilot/MissionPlanner/issues/1456
Cheers, Tridge
CC: @rmackay9

**Comment by mboland** [comment]
Mission Planner can no longer find the binaries for 3.5 beta firmware.
[Forum Issue](http://discuss.ardupilot.org/t/cannot-get-beta-copter-to-appear-in-firmware/16051)

Just wondering when might expect a fix for this?

**Comment by billbonney** [comment]
@Arne-W DO you think you can look at this, sorry I don't have time at the moment

**Comment by Arne-W** [comment]
@billbonney Yes no problem - I will check that tomorrow. BTW you should take a look at #1000 I made a WIP - if yo like it I will make a PR.
