### ISSUE TITLE
Graph: .BIN Logs made with GPXS , GRXH, EKF5 causing slow performance and lots of errors.

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/apm_planner#1022]
[GPS.zip](https://github.com/ArduPilot/apm_planner/files/887828/GPS.zip)

please see attached file, the full file ~80MB takes two minutes to load, and gives >500k "corruption" warnings.

**Comment by Arne-W** [comment]
Okay - one of the problems is that I forgot to implement the parsing of double values :grimacing:  I made a fix for that...
The second problem is that several float and double values resolve to "Not A Number" which results in a drop of the message.
And last but not least - the performance drop is a result of the massive logging in case of such systematic issues.
