### ISSUE TITLE
Map: panning with flightplan

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/apm_planner#1035]
@Arne-W  , please see https://youtu.be/qJW5WLXOkxg
Seems like pan/zoom is not trigging redraw

**Comment by Arne-W** [comment]
I hate this waypoint stuff. I am not sure if we can get it work properly. Does this happen also when downloading waypoints from a FC?

**Comment by AndKe** [comment]
tested:...Works just fine when connected to vehicle.  (both when loaded from plane, and from file..)
this reminds me of how the "mission elevation" widget (very useful) dont work unless connected to an flight controller. - same thing, regardless of mission being on the controller or not, it just don't work if not connected :(

**Comment by Arne-W** [comment]
It was easier than I thought and until now it has no side effects....
If you want to test [https://github.com/Arne-W/apm_planner/tree/BugFixes](https://github.com/Arne-W/apm_planner/tree/BugFixes).
The PR will come...

**Comment by AndKe** [comment]
works fine - thank you.
