### ISSUE TITLE
KMZ export: plane icon orientation is incorrect 

### ISSUE THREAD

**Issue by kd0aij** [ArduPilot/apm_planner#1036]
the heading and RPY angles appear to update only on mode changes:
![plane_icons](https://cloud.githubusercontent.com/assets/2300221/25317170/9065c292-2830-11e7-9ce9-1a277d8a6165.jpg)

**Comment by kd0aij** [comment]
It would also be nice to add Timestamp fields to allow animation and display of a subset of the data.

**Comment by AndKe** [comment]
+1 :)

**Comment by Arne-W** [comment]
As this feature was never implemented this is an enhancement. :smile: 
I made a small - slightly hacky - fix.
If you want to test use this branch: [https://github.com/Arne-W/apm_planner/tree/BugFixes](https://github.com/Arne-W/apm_planner/tree/BugFixes)
I will make a PR in the next days...

**Comment by kd0aij** [comment]
Thanks for the fix; I wouldn't have known where to look...

? I didn't do anything to the plane model; is it a different size in your GE display?

Heading was correct, but roll and tilt needed a signflip: (no idea whether this patch uses QString properly, but it works)
```
diff --git a/src/output/kmlcreator.cc b/src/output/kmlcreator.cc
index 6baa473..c21bc65 100644
--- a/src/output/kmlcreator.cc
+++ b/src/output/kmlcreator.cc
@@ -524,8 +524,9 @@ void KMLCreator::writePlanePlacemarkElement(QXmlStreamWriter &writer, Placemark
 
                     writer.writeStartElement("Orientation");
                     writer.writeTextElement("heading", yaw);
-                        writer.writeTextElement("tilt", a.pitch());
-                        writer.writeTextElement("roll", a.roll());
+                    bool status;
+                        writer.writeTextElement("tilt", QString::number(-a.pitch().toFloat(&status)));
+                        writer.writeTextElement("roll", QString::number(-a.roll().toFloat(&status)));
                     writer.writeEndElement(); // Orientation
                 }
 
```
![signflips](https://cloud.githubusercontent.com/assets/2300221/25407292/09256844-29c7-11e7-9585-c8d795de8cac.jpg)

**Comment by Arne-W** [comment]
Thanks for the info about roll and pitch - changed it :+1: 
The scaling of the plane is weird on my Ubuntu 16.04 with Google Earth 7.1.8.3036 (64-bit) it looks like this:
![gearth](https://cloud.githubusercontent.com/assets/7621911/25431293/3f8235c0-2a80-11e7-9839-a1e6273ecb03.jpeg)

**Comment by kd0aij** [comment]
Looks like the same version of OS and GE, but it will help to get timestamps working so you can reduce the clutter. I'm making progress on that; here's what mine looks like with timestamps added to the plane PlaceMarkers and only 1 second selected:
![1sec](https://cloud.githubusercontent.com/assets/2300221/25436308/25313944-2a50-11e7-9680-3740c0784c10.png)

**Comment by AndKe** [comment]
Google Earth Pro, 7.1.8.3036 (64-bit)
-please observe that the modes are for arducopter, not plane,  
- and yes, the plane symbol is huge, just like yours @Arne-W 


![image](https://cloud.githubusercontent.com/assets/1468842/25450665/e4650cae-2abf-11e7-90f0-f8865d65d166.png)

**Comment by Arne-W** [comment]
Yes, at the moment only a message formatter for copters is used. Should not be a problem to fix that. The logananlysis class which triggers the export "knows" the MAV type so it could pass the type to the exporter. The KML exporter than just has to select the right message formatter.
@kd0aij perhaps you can have a look at this issue too when implementing the new time feature?

**Comment by kd0aij** [comment]
I was wondering about that too; will take a look.
