### ISSUE TITLE
Graph: tlog time on X axis compressed if more than one flight

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/apm_planner#1041]
It's not possible to use time on X-axis for more than first flight in a tlog, the rest (after time loops) is unreadable. (compressed at about 800 seconds.)
It would be nice if graph could somehow handle that, for example, when detecting that time started over, then add time to every timestamp of next flight, or, let user select which flight in the graph to plot.

![screenshot from 2017-05-11 21-22-43](https://cloud.githubusercontent.com/assets/1468842/25968020/54c51be8-3690-11e7-8456-b519b76acf19.png)

**Comment by Arne-W** [comment]
Should be done - nice enhancement.
