### ISSUE TITLE
linux build requires libqt5serialport5-dev, libqt5opengl5-dev and up to date g++, but requires an openssl downgrade (1.0)

### ISSUE THREAD

**Issue by marcmerlin** [ArduPilot/apm_planner#1045]
Could you update the build instructions in README.md ?

I followed the build instructions:
saruman:~/RC/apm_planner$ qmake apm_planner.pro
Project MESSAGE: Qt version 5.7.1
Project MESSAGE: Linux build x64_86
Project MESSAGE: Release flavor
Project MESSAGE: BASEDIR /home/merlin/RC/apm_planner DESTDIR /home/merlin/RC/apm_planner/release TARGET apmplanner2
Project MESSAGE: Using MAVLink dialect 'ardupilotmega'.
Project MESSAGE: Skipping support for Google Earth
Project MESSAGE: Skipping support for libfreenect
Project MESSAGE: Adding ALGLIB /home/merlin/RC/apm_planner/libs/alglib
Project MESSAGE: Skipping support for XBee
Project MESSAGE: Skipping support for Magellan 3DxWare (manual override from command line)
Project MESSAGE: Skipping support for Opal-RT
Project MESSAGE: Skipping support for Google Earth
Project MESSAGE: Skipping support for Camera View
Project ERROR: Unknown module(s) in QT: serialport

So I did
apt-get install libqt5serialport5 libqt5serialport5-dev
qmake worked, but the build failed on 
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h:562:6: error: #error Qt requires a C++11 compiler and yours does not seem to be that.

Next, I installed a later g++ and that fixed that error
Unpacking g++ (4:6.3.0-4) over (4:5.2.1-4) ...

Next failure:
In file included from libs/opmapcontrol/src/mapwidget/gpsitem.h:40:0,
                 from libs/opmapcontrol/src/mapwidget/gpsitem.cpp:28:
libs/opmapcontrol/src/mapwidget/opmapwidget.h:37:30: fatal error: QtOpenGL/QGLWidget: No such file or directory
 #include <QtOpenGL/QGLWidget>

Fix: saruman:~# apt-get install libqt5opengl5-dev

Next, it dies on:
src/ui/configuration/PX4FirmwareUploader.cc: In member function ‘bool PX4FirmwareUploader::checkCOA(const QByteArray&, const QByteArray&, const QString&)’:
src/ui/configuration/PX4FirmwareUploader.cc:644:136: error: invalid use of incomplete type ‘EVP_PKEY {aka struct evp_pkey_st}’
     int verify = RSA_verify(NID_sha1,(unsigned char*)serial.data(),serial.size(),(unsigned char*)signature.data(),signature.size(),pkey->pkey.rsa);
                                                                                                                                        ^~
In file included from /usr/include/openssl/crypto.h:31:0,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:47,
                 from src/ui/configuration/PX4FirmwareUploader.cc:11:
/usr/include/openssl/ossl_typ.h:93:16: note: forward declaration of ‘EVP_PKEY {aka struct evp_pkey_st}’
 typedef struct evp_pkey_st EVP_PKEY;
                ^~~~~~~~~~~
I have libssl-dev:amd64 1.1.0e-2
Sure enough, I have to downgrade openssl:
saruman:~# apt-get install libssl-dev=1.0.1t-1+deb8u6 libssl1.0.0=1.0.1t-1+deb8u6

**Comment by marcmerlin** [comment]
Ok, finally 2h later, finally got a build :)

**Comment by Arne-W** [comment]
@marcmerlin which Linux version are you using?? The openssl issue should be fixed through this #1043. It would be cool if you could verify it. I will add libqt5serialport5-dev and libqt5opengl5-dev to the Readme.

**Comment by Arne-W** [comment]
@marcmerlin if #1043 does not fix the openssl issue could you please test if #1052 does?

**Comment by marcmerlin** [comment]
@Arne-W  this was on debian/testing.
However I see your change was merged on May 24th while I tried to (and failed) to build on May 25th.
But looking at your fix, I'm not sure it would work for me. All you do is ensure that you're linking against an old openssl when you have both on your system.
On debian, you can't have 2 versions of a library's -dev package, so since apmplanner is incompatible with openssl 1.1, my problem is still there after your patch.
For reference on debian the includes are in /usr/include/openssl/ so you can't have 2 versions or point to an older version.

**Comment by Arne-W** [comment]
Open SSL is not needed anymore. See c64ead17c7dc539d65d8bc9deb08284c315162e1
