### ISSUE TITLE
Load scripts trought terminal using APM planner

### ISSUE THREAD

**Issue by Brlma** [ArduPilot/apm_planner#1057]
Hello, 
I am new in using APM planner, Linux and python scripts. I would like to run python scrips to add waypoints in APM planner. I would like to do that through terminal. I was looking for thin on the google, but I could not find the way to do that. Is there any possible way to do that. 

I would be very grateful if someone could help me.

Greetings

**Comment by Arne-W** [comment]
As this is not really an issue but a question, and it was already answered in the forums I will close this now.
