### ISSUE TITLE
qgroundcontrol.pro

### ISSUE THREAD

**Issue by esromerom** [ArduPilot/apm_planner#1066]
Where is the file qgroundcontrol.pro to make the qmake thing? 
Or I am missing a step to create it? Does anybody knows?

**Comment by auturgy** [comment]
try working through the guide in README.md using apm_planner.pro from the top level directory.

**Comment by esromerom** [comment]
That's it. Already tried and its done! Thanks you

**Comment by Arne-W** [comment]
@esromerom - Is there a reason for reopening or was it just by accident??

**Comment by Arne-W** [comment]
ok - will close it now
