### ISSUE TITLE
NaN in dataflash POS.RelOriginAlt in not an error

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/apm_planner#1067]
NaN's are intentionally encoded before the EKF has booted, this is not an error on this message. https://github.com/ArduPilot/ardupilot/pull/6607

```
Logline 15264: Corrupt data element found when decoding POS data.
Logline 15264: No values within data message
```

**Comment by Arne-W** [comment]
@WickedShell Ok - shouldn' t be a problem to fix that. I will have a look in the next days. It would be great if you could provide a log I can work with.
