### ISSUE TITLE
arm throttle in Mission Planner 1.3.50

### ISSUE THREAD

**Issue by blodyshadow** [ArduPilot/apm_planner#1072]
hi,
in mission planner precious version, ther is an“Arm/Disarm” button that can be used to arm and disarm the throttle. How do I do it in 1.3.50 version mission planner?

**Comment by Arne-W** [comment]
Hmm I am sorry, but I have to tell you that this is **not** the Mission Planner repository. This is APM-Planner repo. We can answer questions about APM-Planner :smile:

**Comment by auturgy** [comment]
Missionplanner issues are here:
https://github.com/ArduPilot/MissionPlanner/issues
