### ISSUE TITLE
MAVLink statistics

### ISSUE THREAD

**Issue by guglie** [ArduPilot/apm_planner#1075]
Hi, how can I see MAVLink statistics (packets received, packets loss, ...) in APM Planner?

**Comment by Arne-W** [comment]
At the moment it isn't possible I think. In Advanced Mode you can find a Tool Widget called MAVLink Inspector, perhaps it gives you some of the informations you need?!

**Comment by guglie** [comment]
Thank you, but it doesn't shows these stats...

**Comment by Arne-W** [comment]
Perhaps you can add them to the inspector?! Would be cool :wink:

**Comment by Arne-W** [comment]
@guglie I made a PR #1149 which adds simple statistics to the mavlink inspector - perhaps you want to test :smiley:

**Comment by Arne-W** [comment]
fixed with adb583fc74f94f4b4b436f81d6e24f40368e115d
