### ISSUE TITLE
Time for a README.md update?

### ISSUE THREAD

**Issue by drobban** [ArduPilot/apm_planner#1077]
First time submitting an issue and I'm not sure that my report belong here.

During the time I have been waiting for my quadcopter building material to arrive, I have spent some time reading and testing apm planner2 with simulator. 

In this process I have relied on much of the information provided in the README and discovered at least one broken link and a suggestion for improvement.

Link that is broken is: 
http://planner2.ardupilot.com 
I suspect that the correct is: http://ardupilot.org/planner2/

In the building instructions for Linux, you provide information about "tested" Linux distribution.
Perhaps an improvement would be to provide a table of reported systems that users have been testing the software in.

**Comment by billbonney** [comment]
fixed, thx 👍

**Comment by drobban** [comment]
hehe :) I hoped that I could get to make a pull request for that one...
Well, perhaps I can find something else in the future to improve.

**Comment by billbonney** [comment]
@drobban Sure, please make a PR and we can review and commit the changes. Contributions are more than welcome. 😄
