### ISSUE TITLE
Auto aborted in Remotedesktop

### ISSUE THREAD

**Issue by cn1995640** [ArduPilot/apm_planner#1081]
I launched the wonderful application in Pi3B with remote mode, It's seem's all right when started the window, then it failed to create OpenGL and aborted.

**Comment by Arne-W** [comment]
@cn1995640 So you need OpenGL on the target system - but what is the issue?

**Comment by cn1995640** [comment]
@Arne-W Thanks!

**Comment by Arne-W** [comment]
Ok :smiley: than I will close this issue.
