### ISSUE TITLE
Can't connect APM to Mac OS High Sierra

### ISSUE THREAD

**Issue by barcia** [ArduPilot/apm_planner#1094]
I am trying to connect my Cheerson CX 20 with APM to my Mac OS High Sierra but not show the usb port. I install the FTDIUSBSerialDriver that is inside the .dmg, but not works.

**Comment by billbonney** [comment]
You probably need to use the other USB driver as the Cheerson has a different USB chip

For support use this forum https://discuss.ardupilot.org/c/ground-control-software/apm-planner-2-0

and this question maybe the solution

https://discuss.ardupilot.org/t/solved-3dr-telemetry-wont-work-on-osx/18574
