### ISSUE TITLE
Graph: Table filter text matching

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/apm_planner#1100]
To reproduce;
Load dataflashlog (Copter log with TERR /ERR messages) 
in table filter , select only ERR messages.

Observe that the table will contain TERR, as well as the expected ERR messages.

Same is true when selecting IMU, then  IMU2,IMU3 will show as well.

**Comment by Arne-W** [comment]
Yes I know - there is a but in the regex creation - should be fixed
