### ISSUE TITLE
Unable to parse log

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/apm_planner#1106]
APM planner version： 2.0.24
ardupilot version：copter 3.8.4

![_20180306105030](https://user-images.githubusercontent.com/16251761/37011712-424f5b36-212c-11e8-8327-c9c904a18bdf.png)

**Comment by Arne-W** [comment]
@liang-tang I strongly recommend to update your APM-Planner version. I would recommend to use 2.0.26-rc1 which can be found [here](http://firmware.ardupilot.org/Tools/APMPlanner/beta/), or look in the [discussion forums](https://discuss.ardupilot.org/c/ground-control-software/apm-planner-2-0) there are several topics containing a 2.0.25 version for various plattforms.
Or build from scratch by yourself.
Between 2.0.24 and 2.0.25 the log parsing has been completely rewritten and 2.0.26 adds a lot of bugfixes to several parts of the APM-Planner

**Comment by liang-tang** [comment]
@Arne-W Thanks very much，I have update apm-planner to 2.0.26

**Comment by Arne-W** [comment]
:+1: that version should work like a charm... :smiley:
