### ISSUE TITLE
error building on RPi 2 running Ubuntu. will not release.

### ISSUE THREAD

**Issue by verkoda** [ArduPilot/apm_planner#1114]
It appears to have reashed the end of building, but I'm given the error
    build-release/obj/qrc_qgroundcontrol.o: file not recognized: File truncated
    collect2: error: ld returned 1 exit status
    Makefile:1717: recipe for target 'release/apmplanner2' failed
    make: *** [release/apmplanner2] Error 1

Also, how do I syntax code on here?

**Comment by Arne-W** [comment]
Never build for RPi2 but perhaps @dcarpy has an Idea?

**Comment by dcarpy** [comment]
There should be a compile error somewhere before the above error you are seeing.

**Comment by Arne-W** [comment]
@verkoda Is this still an issue?
Otherwise I will close it in the next week.

**Comment by Arne-W** [comment]
As there was no answer - I close this now
