### ISSUE TITLE
waypoint markers gone if connected to vehicle.

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/apm_planner#1117]
In current master, once AP2 connects to a vehicle (sitl too) , the waypoints will loose the markers and  become un-dragable.
![screenshot from 2018-04-13 07-03-57](https://user-images.githubusercontent.com/1468842/38717777-4f186cba-3ee9-11e8-905a-dfbf4d0577bb.png)

**Comment by AndKe** [comment]
Important clue: this happens when the vehicle has a mission consisting off "terr.alt" waypoints.

**Comment by Arne-W** [comment]
Do all waypoints have to be "terr.alt" waypoints or only one or some in that in that track?
Does it also happen in the 2.0.25 version?
Would be very cool if you could check that.

**Comment by AndKe** [comment]
It happens only to ter.alt waypoints, and only on load/creation.
changing the coordinate frame of a waypoint does not make the box spawn instantly.
