### ISSUE TITLE
Documented build as .deb does not work

### ISSUE THREAD

**Issue by flohoff** [ArduPilot/apm_planner#1128]
The Documented way to using debbuild to build a .deb does not work as there is no changelog:

a) Using Debuild:

cd ~/workspace/apm_planner
debuild -us -uc -d

flo@p4:~/projects/apm_planner$ debuild -us -uc -d
debuild: fatal error at line 660:
cannot find readable debian/changelog anywhere!
Are you in the source code tree?

Flo

**Comment by dcarpy** [comment]
cd ~/workspace/apm_planner/debian
./gitlog-to-changelog.pl > changelog
