### ISSUE TITLE
Problem with Arducopter 3.6 and Extended Tuning

### ISSUE THREAD

**Issue by anbello** [ArduPilot/apm_planner#1138]
With Arducopter 3.6 (dev and rc6) if I try to open the Extended Tuning page APM Planner does nothing, I think this is related to the change of some parameters name from 3.5 to 3.6 as explained by  @rmackay9 in this issue on Mission Planner repository:
https://github.com/ArduPilot/MissionPlanner/issues/1903

**Comment by Arne-W** [comment]
Can reproduce this issue with SITL.

**Comment by Arne-W** [comment]
@anbello see #1140 - should fix the issue

**Comment by anbello** [comment]
@Arne-W OK I tested #1140 and it fixed the issue
thanks a lot

**Comment by Arne-W** [comment]
@anbello always welcome - and thanks for testing :+1:
