### ISSUE TITLE
Graph: Use of exponent

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/apm_planner#1150]
Please observe the range for battery % 
always using exponent reduces readability.
![screenshot from 2018-08-24 12-20-38](https://user-images.githubusercontent.com/1468842/44628724-0155b880-a946-11e8-9377-322bd3eba375.png)

**Comment by Arne-W** [comment]
You are right - does not look good. At the moment the scaling is done automagically by the graphing framework - perhaps we can force it to use exponents only when using bigger numers....
