### ISSUE TITLE
Please add support for dataflash log review of latest ArduPilot Firmware

### ISSUE THREAD

**Issue by SwiftGust** [ArduPilot/apm_planner#1152]
I really liked using APMplanner2 for reviewing dataflash log.
It gives great automatic scaling, coloring, event messages...
However, now it looks like APMplanner2 does not compatible with datalog of latest ArduPilot firmware
Please add support for latest dataflash log of ArduPilot 

![image](https://user-images.githubusercontent.com/13569579/45282054-c7271200-b514-11e8-938e-5caefea722f4.png)
![image](https://user-images.githubusercontent.com/13569579/45282195-37359800-b515-11e8-8eb5-5e1b9fcf849c.png)

**Comment by Arne-W** [comment]
@SwiftGust please update to APM-Panner 2.0.26-rc2 which can be found [here](http://firmware.ardupilot.org/Tools/APMPlanner/beta/). It is the last released stable version.
If you want the newest stuff - should be very stable too - you could look in [in this forum post](https://discuss.ardupilot.org/t/arducopter-3-6rc-ctun-parameter-not-recognized/31766). The win 64 installer should be build from the current master.

**Comment by SwiftGust** [comment]
Thank you for quick reply.
It works fine,
but has little problem with ArduCopter dataflash...

![image](https://user-images.githubusercontent.com/13569579/45283597-474f7680-b519-11e8-86f3-ef8b9794b1d6.png)

**Comment by Arne-W** [comment]
@SwiftGust Yes its a known problem - see the Forum post - that version should fix it. Moreover the error message is no problem an can be ignored....

**Comment by SwiftGust** [comment]
Yes, no problem at all for reviewing flight data. 
Thanks
