### ISSUE TITLE
Problem with Arducopter 3.6, MAVLink2 and Radio Calibration Page

### ISSUE THREAD

**Issue by anbello** [ArduPilot/apm_planner#1153]
If I set SERIAL0_PROTOCOL = 2 (MAVLink2) then on Radio Calibration Page I see all values 0 and the graphics don't follows my sticks, in MAVLink Inspector I see the correct values.
With SERIAL0_PROTOCOL = 1 (MAVLink1) is all OK.

[EDIT]
I am using APM Planner v2.0.26-rc2 (2.0.26-23-g718b06e)

**Comment by Arne-W** [comment]
@anbello 2.026-rc2 does not have support for MAVLink 2 - sorry. We introduced the MAVLink2 support right after the las release. If you want to use MAVLink2 you will have to take the current master.
If you are on Windows you could find a build of the master [in this forum post](https://discuss.ardupilot.org/t/arducopter-3-6rc-ctun-parameter-not-recognized/31766/8). If you are on linux I can try to build a version for you this evening and if you are on mac you sould look [here](http://firmware.ardupilot.org/Tools/APMPlanner/daily/2018-08-30/)

**Comment by anbello** [comment]
The version I am using and for which I report this issue is built by me from master (commit 718b06e).
What I wrote under [EDIT] is the version reported from Help -> About.

**Comment by Arne-W** [comment]
Ah - Ok (did not check the git hash) I will try to reproduce it in the naxt days....

**Comment by Arne-W** [comment]
Could reproduce this issue yesterday. Looks like the MAVLink message ID has changed cause MAVLink 2 message supports 16 RC channels. I hope I can fix it and perhaps extend the gui to show all 16 channels on next weekend...

**Comment by Arne-W** [comment]
@anbello If you like you can test [my branch](https://github.com/Arne-W/apm_planner/tree/rc_channels). It should fix this issue and show all 16 chnnels. It is still a WIP so if you have some Ideas for making it better - just let me know.

**Comment by anbello** [comment]
I am sorry for so late replay. Unfortunately, in this period I have little time for these stuff.
Anyway I tested your branch and it works good for me.
