### ISSUE TITLE
Graph: .tlog export to KML/KMZ

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/apm_planner#1154]
the export appears to work, but the resulting .kmz does not have any flight-based content (no positions/modes/etc)

**Comment by Arne-W** [comment]
Exporting a tlog to a KML has never worked as the kml exporter tries to find special message names which are used in flashlogs. The messages in tlogs have different names...
The whole exporting for KML is not very good as we will get problems with scaled logs too. We need some sort of redesign...

**Comment by Arne-W** [comment]
...perhaps we should disable the kml export for tlog files.

**Comment by Arne-W** [comment]
Disabled the kml export for all but flashlogs. 
Fixed with e2a15de5294d8bd67be2cbc0d84606d663f20c47
