### ISSUE TITLE
Altitude Angel missing in v2.0.27-rc1

### ISSUE THREAD

**Issue by vmajor** [ArduPilot/apm_planner#1165]
I built v2.0.27-rc1 from source on Ubuntu 18.04 and I do not get a request to log into Altitude Angel like I do when I run precompiled APM in Windows 10.

There are no errors reported in the terminal or in the debug console (identical output)

**Comment by Arne-W** [comment]
Sorry but I do not understand what you mean with " log into Altitude Angel"

**Comment by vmajor** [comment]
Yes, sorry about that. I'm not as new to this field anymore.

I was confusing apm_planner with Mission Planner.

**Comment by Arne-W** [comment]
Ahh - so we can close this issue ?

**Comment by vmajor** [comment]
Definitely closed.

**Comment by Arne-W** [comment]
Thank you for the fast response :+1:
