### ISSUE TITLE
APM Planner 2.0 cannot be opened 

### ISSUE THREAD

**Issue by deandrecapati** [ArduPilot/apm_planner#1172]
I'm trying to install APM Planner for macOS Mojave, but it won't let me open the program. I tried reinstalling the program as suggested, but not luck. Anyone have any suggestions on the issue or know about the issue?

**Comment by Arne-W** [comment]
@deandrecapati did you use the newest version? 
Please try this version: [http://firmware.ardupilot.org/Tools/APMPlanner/daily/2019-03-08/apm_planner_2.0.27-rc1-7-g299ff23_osx.dmg](http://firmware.ardupilot.org/Tools/APMPlanner/daily/2019-03-08/apm_planner_2.0.27-rc1-7-g299ff23_osx.dmg)

**Comment by kelechiokwuriki** [comment]
My macos version is Catalina 10.15.3 but it still did not open when i tried to install

**Comment by mboland** [comment]
Did you allow it to open in System Preferences/Security & Privacy/General/app Store and Identified Developers?

**Comment by MonkeyManGuy** [comment]
> Did you allow it to open in System Preferences/Security & Privacy/General/app Store and Identified Developers?
> Works fine here on 10.15.4

All Mac users are accustomed to doing that.

Catalina 10.15.6 here and I get a message saying APM Planner is not compatible with this version of OSX. This is after a fresh install

**Comment by mboland** [comment]
@MonkeyManGuy 
I am currently using 10.15.6 without issue.
The ‘not compatible’ message is usually for 32bit applications.
Does it have a circle with slash through it on the icon.

**Comment by MonkeyManGuy** [comment]
Take a look at these screenshots:

**Comment by billbonney** [comment]
Just download the latest release candidate and you will be golden! https://github.com/ArduPilot/apm_planner/releases

**Comment by MonkeyManGuy** [comment]
This are the pictures I meant to get attached. These were taken on 7.31.2020 with the latest download. But I will uninstall it and try again with the latest download once more & report back.

<img width="1324" alt="Screen Shot 2020-07-31 at 2 47 38 PM" src="https://user-images.githubusercontent.com/56900581/89337358-d2373e00-d668-11ea-98e1-3ed9a8746ecf.png">


<img width="997" alt="Screen Shot 2020-07-31 at 2 48 44 PM" src="https://user-images.githubusercontent.com/56900581/89337349-cf3c4d80-d668-11ea-9df6-ff6f790cd42e.png">

**Comment by MonkeyManGuy** [comment]
It happens again. Ive opened up the details this time and it shows something interesting:
<img width="1440" alt="Screen Shot 2020-08-04 at 3 45 49 PM" src="https://user-images.githubusercontent.com/56900581/89337857-ab2d3c00-d669-11ea-88d8-b936a70c5dbb.png">
![Uploading Screen Shot 2020-08-04 at 3.45.00 PM.png…]()

**Comment by mboland** [comment]
Firstly, the FTDI driver package IS NOT compatible.
As in its name on the drive 10.4 to 10.7
You should not need to install drivers on 10.15

Installing is just a matter of dragging APM into your Apps folder 
The message you get is a little different

To illustrate I did a fresh download from the Link @billbonney provided above 
1: just drag the APM-P into your app folder from the downloaded .dmg package
![Screen Shot 2020-08-05 at 6 32 11 am](https://user-images.githubusercontent.com/3221133/89342269-e2413300-d6e5-11ea-954a-119ec9373860.png)
When you double click it you will get this message
![Screen Shot 2020-08-05 at 6 32 28 am](https://user-images.githubusercontent.com/3221133/89342325-f8e78a00-d6e5-11ea-9bfe-e14549bcd34f.png)
Go to System Preferences/Security & Privacy and click ‘Open Anyway’ You may need to unlock the pane first.
![Screen Shot 2020-08-05 at 6 32 56 am](https://user-images.githubusercontent.com/3221133/89342492-351aea80-d6e6-11ea-8a68-859098d231e0.png)
When it opens you will get an additional warning
![Screen Shot 2020-08-05 at 6 33 13 am](https://user-images.githubusercontent.com/3221133/89342539-4532ca00-d6e6-11ea-84ac-23c08329b500.png)
Click open and all is done.

**Comment by drobban** [comment]
> I had been downloading the software from here in the 3 times Ive attempted it since posting here: https://firmware.ardupilot.org/Tools/APMPlanner/
> 
> Perhaps the downloads on the main site need to be updated?
> 
> > Just download the latest release candidate and you will be golden! https://github.com/ArduPilot/apm_planner/releases
> 
> Where in this link can a DMG file be found? I see no installer on there. I tried downloading the Zip and Tar.gz and neither contained an application or dmg file.
> 
> mboland,
> 
> Where exactly on that page did you find a file that was able to get an installer open on your Mac?
https://ardupilot.org/planner2/docs/installing-apm-planner-2.html
https://firmware.ardupilot.org/Tools/APMPlanner/

**Comment by drobban** [comment]
Did a fast and a furious click the links as presented for me according to README and then documentation.
Ended up at https://firmware.ardupilot.org/Tools/APMPlanner/ and that site seems to be outdated?

Is this the official source of builds: https://github.com/ArduPilot/apm_planner/releases

> Where exactly on that page did you find a file that was able to get an installer open on your Mac?
There is a link under the latest release labeled "Assets", click that and you find the latest .DMG

**Comment by drobban** [comment]
After reading the comment history, I get the feeling that all reported problems might come from that people are using the old builds served from https://firmware.ardupilot.org/Tools/APMPlanner/.

If so, updated README with current installation information and this issue looks to be resolved?

**Comment by ferremek** [comment]
Hey guys,

Have downloaded release 2.0.28-rc1 from https://github.com/ArduPilot/apm_planner/releases/tag/2.0.28-rc1. But I cannot install the driver because there is a warning it's not compatible. I have macOS Big Sur 11.1 installed on a MacBook Pro 2018.

Any suggestions how to fix this issue?

Thanks!

**Comment by billbonney** [comment]
The driver is now built-in to macOS. You don’t need to install it. Apm  planner 2.0 will work just fine

**Comment by Iragne** [comment]
@Arne-W & @billbonney  Do you think this issue can be closed ?

**Comment by Arne-W** [comment]
@Iragne Yes you are right - thanks for reviewing.
