### ISSUE TITLE
Compiling with QT on Raspberry Pi or Desktop

### ISSUE THREAD

**Issue by benb0jangles** [ArduPilot/apm_planner#1183]
Simple question, but are you successfully compiling on QT natively on the Raspberry Pi or Successful using X86/X64 Ubuntu Desktop to remotely compile for Raspberry Pi?

**Comment by Arne-W** [comment]
If you want to build for raspberry pi you should look [HERE](https://github.com/ArduPilot/apm_planner/issues/1178).
If building for Ubuntu x86 / x64 it should work using the infos you can find in the readme.md

**Comment by benb0jangles** [comment]
Thanks, already success building for x86/x64, wanting to build for armhf

**Comment by dcarpy** [comment]
Increase/create some swap space on the Pi.
https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

**Comment by benb0jangles** [comment]
Increasing the Swap File from the default 100MB to 1024MB appears to have solved the issue.
