### ISSUE TITLE
cannot download apm planner on mac os 10.15.1

### ISSUE THREAD

**Issue by Johanth3108** [ArduPilot/apm_planner#1190]
when i download the zip file and try to install the software i cannot install it, my os is catalina.

**Comment by yuruyenadam** [comment]
i have same issue what should i do?

**Comment by Arne-W** [comment]
Which zip file are you talking about? 
Use this: [https://firmware.ardupilot.org/Tools/APMPlanner/daily/2019-03-08/apm_planner_2.0.27-rc1-7-g299ff23_osx.dmg](https://firmware.ardupilot.org/Tools/APMPlanner/daily/2019-03-08/apm_planner_2.0.27-rc1-7-g299ff23_osx.dmg)

**Comment by Arne-W** [comment]
Is this still an issue? If not could you please close it?!

**Comment by scientistbala** [comment]
hi sir,
I have the same issues, my OS is Catalina ver 10.15.7.
I tried to install mission planner its showing error.
I attached the image below, how to fix this
![Screenshot 2021-01-08 at 11 56 48 AM](https://user-images.githubusercontent.com/77141028/103981898-b18b8b00-51a8-11eb-9cd4-bda071e0003f.png)
