### ISSUE TITLE
APM Planner 2.0” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by kelechiokwuriki** [ArduPilot/apm_planner#1203]
I have tried to install APM planner on my mac os Catalina Version 10.15.3 but it gives me the error stated on the title of this issue. What do i do?

**Comment by mboland** [comment]
Did you allow it to open in System Preferences/Security & Privacy/General/app Store and Identified Developers?
Works fine here on 10.15.4

**Comment by billbonney** [comment]
see https://support.apple.com/en-nz/guide/mac-help/mh40616/mac on how to open this unsigned package
