### ISSUE TITLE
./release/apmplanner2: No such file or directory

### ISSUE THREAD

**Issue by Babars7** [ArduPilot/apm_planner#1211]
Hey!
I am installing apm_planner for my raspberry pi using the linux installation process. But after buiding APM PLanner I have nothing in release folder. What I did wrong ?

**Comment by Arne-W** [comment]
Sorry but this question is somewhat unspecific - there could be 1000 reasons for that.
Try to tell what you did and what happened. Were there any problems during compiling or while configuring??
