### ISSUE TITLE
Not able to view the Models and Menu after opening Initial setup (PX4 Connected)

### ISSUE THREAD

**Issue by liox1985** [ArduPilot/apm_planner#1214]
Dear Experts,

Not able to view the menu after connecting PX4 (FMU2.x) using USB port 
Apple OS - 10.15.3 (Catalina)
APM Version 2.0.26-2c1 

Kindly assist .. Please refer attached pic

![Uploading Screenshot 2020-06-17 at 15.48.18.png…]()

**Comment by liox1985** [comment]
<img width="1280" alt="Screenshot 2020-06-17 at 15 48 18" src="https://user-images.githubusercontent.com/64191743/84992454-889c9d80-b165-11ea-8213-19e6f0be4e53.png">

**Comment by Arne-W** [comment]
Please stop spamming

**Comment by liox1985** [comment]
Hi Team , Its not spam facing genuine issue with software to connect.

Please advice.

**Comment by billbonney** [comment]
Use the latest release https://github.com/ArduPilot/apm_planner/releases and please look on the forum. (You have askes this question twice hence the spam reference)
