### ISSUE TITLE
Crashed Thread:  23  QSGRenderThread

### ISSUE THREAD

**Issue by CMullins2020** [ArduPilot/apm_planner#1219]
OS Version:            Mac OS X 10.15.6 

Crashed Thread:        23  QSGRenderThread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [61604]

Application Specific Information:
-[NSOpenGLContext setView:] must be called from the main thread.

**Comment by Arne-W** [comment]
Is this still an issue - otherwise I will close it in the next days
