### ISSUE TITLE
qmake many features disabled

### ISSUE THREAD

**Issue by brcisna** [ArduPilot/apm_planner#1221]
Hello All,

Can anyone enlighten in regards to when you run qmake on apm_planner it indicates many features 'will not be used'. Google maps,,and many others.

Thank You

**Comment by drobban** [comment]
would guess it depends on what dependencies you have installed? But not sure what you mean.

**Comment by Arne-W** [comment]
@brcisna Sorry it took so long to get an reply. You can ignore those messages. They are from some experimental features and are not relevant for the apm planner functionality.

**Comment by Arne-W** [comment]
closing now...
