### ISSUE TITLE
Is this software still under active development?

### ISSUE THREAD

**Issue by xilh** [ArduPilot/apm_planner#1222]

**Comment by drobban** [comment]
look at the commit history is a good start

**Comment by billbonney** [comment]
Yes. Maintenance and some development. Feel free to contribute.

**Comment by Arne-W** [comment]
@xilh currently only maintenance because I have too little free time. But as bill said - feel free to contribute new features or bug fixes are always welcome.

**Comment by amilcarlucas** [comment]
Can this issue be closed now?

**Comment by Arne-W** [comment]
@xilh @amilcarlucas Yes I think it can be closed 😃
