### ISSUE TITLE
MacOS BigSur

### ISSUE THREAD

**Issue by elenagin** [ArduPilot/apm_planner#1233]
Hello, can't download using MacOS BigSur, will it be available for this version of MacOS any time soon ? Thank you!

![image](https://user-images.githubusercontent.com/32081397/107107232-7dca7200-67f5-11eb-9acb-b6cf8d97b7d1.png)
![image](https://user-images.githubusercontent.com/32081397/107107616-cedb6580-67f7-11eb-98df-ab53fee03abe.png)

**Comment by billbonney** [comment]
You do not need the FTDI drivers as they are for OSX up to 10.7. It's been built in ever since

**Comment by elenagin** [comment]
Just needed to restart my computer and it worked! Thank you very much :)
