### ISSUE TITLE
PFD Altitude >1000m - display error.

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/apm_planner#1239]
![Screenshot from 2021-04-17 19-45-43](https://user-images.githubusercontent.com/1468842/115126501-b9d93a80-9fcf-11eb-8734-806bda0b4911.png)

The altitude tape ends, and both the first digit and the decimal is gone.
A quick fix could be to align the text so that the four first digits were visible (and the decimal gone)

**Comment by Arne-W** [comment]
@AndKe will 2000m be enough?

**Comment by AndKe** [comment]
@Arne-W  Yes, even for operations at high elevations, 2000 should be fine.  (I am surprised that you ask, because I would just think this is a formatting-logic issue and once fixed, anything to 9999 would work.)

**Comment by Arne-W** [comment]
@AndKe Yes the formatting changed - removed the decimal when higher than 100m. But the scrolling numbers thingy (no Idea how to call them) ended at 1000m they will now end at 2000m.

**Comment by AndKe** [comment]
Thank you for fixing the speed tape,  (also known as "scrolling numbers thingy")
:)

**Comment by billbonney** [comment]
Apologies. I should have realized that people may fly over 120m (400ft) :-o

**Comment by AndKe** [comment]
Yes, that may be less common, but even relatively standard commercial mapping flights of some rivers between a dam, and sea level, can require >1000m AMSL or relative altitude indication, while barely being over 100m AGL at most. (usually in the steepest parts)
