### ISSUE TITLE
SegFault while connecting over UDP to simulated px4 vehicle

### ISSUE THREAD

**Issue by nabinodd** [ArduPilot/apm_planner#1244]
Starts and runs normally with a serial connection to a pixhawk hardware.
Crashes immediately after loading some parameters(as seen in console log) while connecting over UDP.
[apmplanner2_crash.log](https://github.com/ArduPilot/apm_planner/files/6570752/apmplanner2_crash.log)

Distributor ID : Ubuntu
Description : Ubuntu 20.04.2 LTS
Release : 20.04
Codename : focal
apm : https://firmware.ardupilot.org/Tools/APMPlanner/apm_planner_2.0.26_bionic64.deb

**Comment by Arne-W** [comment]
@nabinodd  The version you are using is outdated. Please use this one:
[https://github.com/ArduPilot/apm_planner/releases/tag/2.0.29-rc1](https://github.com/ArduPilot/apm_planner/releases/tag/2.0.29-rc1)
There you will find an Appimage.
