### ISSUE TITLE
Graph: Something odd happens with MSG display when using time on X-axis

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/apm_planner#1246]
![Screenshot from 2021-07-02 08-55-07](https://user-images.githubusercontent.com/1468842/124233898-a5f39e00-db13-11eb-8ab8-4e4c3ca43e68.png)

Please observe the strange order of waypoints.  It depend on "use time on x-axis"
Full log: https://drive.google.com/file/d/1Yo4zXbEi2yZXjywz2OkLQIav8RNsq_Ux/view?usp=sharing

**Comment by Arne-W** [comment]
@AndKe I hope I will have some time during my holiday to check these issues.

**Comment by AndKe** [comment]
Well done, thank - i imagined this to require a much more complex solution.
