### ISSUE TITLE
Graph: issue with time between, and incorrect mode changes

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/apm_planner#1251]
Please see described log here: https://drive.google.com/file/d/1SOBGs9QMW2ZKAVyC0Fy1heO6wfvezv4T/view?usp=sharing

Loading this log (various text unchecked) shows actual activity if I select altitude (or other data that indicate use)
![Screenshot from 2021-11-03 18-38-51](https://user-images.githubusercontent.com/1468842/140163346-262ebe31-cb36-45cb-9074-c53ec9f2c8f5.png)

Zooming in, reveals repeating mode-changes (that are not real)
![Screenshot from 2021-11-03 18-39-24](https://user-images.githubusercontent.com/1468842/140163514-3521118e-de97-45e8-a023-90deb9ad8db6.png)

Otherwise, it works great. :)

**Comment by AndKe** [comment]
@Arne-W  - I kind of feel as if you have commented on both issues before, but can't find such thread.

**Comment by Arne-W** [comment]
@AndKe The problem are the GCS messages which were treated as vehicle messages. That was easy to fix. But this log has several issues with the timeline. There are a lot of jumps and as you can see the log duration it is more than 417881829,395 YEARS :smile:

**Comment by AndKe** [comment]
@Arne-W   Thank you !
