### ISSUE TITLE
"Install Firmware" gives server error output

### ISSUE THREAD

**Issue by yasemindeki** [ArduPilot/apm_planner#1258]
"Install Firmware" gives the following error output:
Started downloading http://firmware.ardupilot.org/Copter/stable/PX4-quad/ArduCopter-v2.px4
redirect to https://firmware.ardupilot.org/Copter/stable/PX4-quad/ArduCopter-v2.px4
Error downloading firmware.
Error Number: 203
Error Text: Error transferring https://firmware.ardupilot.org/Copter/stable/PX4-quad/ArduCopter-v2.px4 - server replied: Not Found

**Comment by yasemindeki** [comment]
"PX4-quad" named folder does not exist in https://firmware.ardupilot.org/Copter/stable/ address.

**Comment by Arne-W** [comment]
@yasemindeki Please use this version: [https://github.com/ArduPilot/apm_planner/releases/tag/2.0.29-rc1](https://github.com/ArduPilot/apm_planner/releases/tag/2.0.29-rc1)

**Comment by yasemindeki** [comment]
Thank you so much.
