### ISSUE TITLE
Mac // APM Planer 2.0 not connecting to FC but QGroundControl can / does automatically with success. (Big Slur & Ventura)

### ISSUE THREAD

**Issue by JulianGoesPro** [ArduPilot/apm_planner#1264]
I am primarily using my MacBook and moved from iNav to ArduPlane for a T1-Ranger VTOL build.

My FC (H743) connects flawlessly on iNav in the iNav configurator and connects to QGroundControl after flashing ArduPlane automatically, but when "connecting" in AP Planer 2.0, nothing happens, the artificial horizon stays locked... I am not sure it's actually connecting or even trying to connect since the GUI shows "connected" instantly when clicking on it.

<img width="1440" alt="Screenshot 2022-07-12 at 17 11 42" src="https://user-images.githubusercontent.com/11023597/178526712-1839902d-04c7-401d-b485-17e93c20e5c9.png">
<img width="1440" alt="Screenshot 2022-07-12 at 17 14 02" src="https://user-images.githubusercontent.com/11023597/178526733-6006e6c2-8771-4ee2-a82c-841407f90029.png">
<img width="1440" alt="Screenshot 2022-07-12 at 17 15 09" src="https://user-images.githubusercontent.com/11023597/178526735-36f5363e-8f93-4ccf-925c-f152e5f7d089.png">
<img width="1440" alt="Screenshot 2022-07-12 at 17 15 18" src="https://user-images.githubusercontent.com/11023597/178526752-96945883-2691-4d7f-8673-97bc168d2f33.png">

Would be awesome if anyone could direct me to something to try or to look up to get to the bottom of this... so weird...

Thank you!

**Comment by Arne-W** [comment]
@JulianGoesPro Please use [this version](https://github.com/ArduPilot/apm_planner/releases/download/2.0.29-rc1/apm_planner_2.0.29-rc1_osx.dmg) which can be found [here](https://github.com/ArduPilot/apm_planner/releases/tag/2.0.29-rc1)

**Comment by JulianGoesPro** [comment]
@Arne-W Thank you very much... got a crash first but now it's connecting! Awesome!
<img width="1440" alt="Screenshot 2022-07-16 at 11 39 10" src="https://user-images.githubusercontent.com/11023597/179349577-edf5553d-3885-4fc2-895e-b772b34b0ba0.png">
<img width="1440" alt="Screenshot 2022-07-16 at 11 41 20" src="https://user-images.githubusercontent.com/11023597/179349578-90655658-8e82-45bf-ade8-08687a27d81b.png">
<img width="1440" alt="Screenshot 2022-07-16 at 11 39 10" src="https://user-images.githubusercontent.com/11023597/179349580-c7c569a3-a21c-4bb7-98ec-3fd9a5b0b3d5.png">

**Comment by Arne-W** [comment]
seems to be solved :smiley:
