### ISSUE TITLE
APM Planner 2 does not show firmwares 

### ISSUE THREAD

**Issue by huseyinefe** [ArduPilot/apm_planner#1277]
I connect the arducopter my laptop. Then I opened APM2 planner. Then I entered firmware and I chosed the COM. But I could not see anything.
![2023-02-15_11-39-59](https://user-images.githubusercontent.com/43684731/218977671-6fbccb68-5111-450e-a42a-b64ed5ea24c3.png)

**Comment by Arne-W** [comment]
@huseyinefe use a newer version. [You can find them here](https://github.com/ArduPilot/apm_planner/releases)

**Comment by Arne-W** [comment]
looks like it was solved...
