### ISSUE TITLE
Graph view: Flight modes displayed as numbers for quadplane

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/apm_planner#1285]
Flight modes are displayed as numbers, this may be related to newer ArduPilot releases or quadplane modes.
Traditional flight modes from the copter and plane logs work as expected.

the modes (QLOITER, QHOVER, CRUISE) are all found in uas/ArduPilotMegaMAV.h

A Qplane log: https://drive.google.com/file/d/1raW4YJSFi2nYCjZ728s9boFaHuqKqpNS/view?usp=sharing

@Arne-W  - is there a chance you can look at it?

**Comment by AndKe** [comment]
@Arne-W  Thank you very much - in two days I am going away on a vacation without my laptop, so I can enjoy the results after 30 June.  Have a great summer.

**Comment by AndKe** [comment]
Hi, I am still on vacation, but I see your recent commits and all the good stuff you added. Thank you!

**Comment by Arne-W** [comment]
@AndKe You are always welcome - If I have the time I do my best :smile:

**Comment by AndKe** [comment]
@Arne-W  With a log from Arduplane 4.4.0 : I still see the numbers with AP2.0.30
Please try https://drive.google.com/file/d/1mW0g0orfJ7wGICsTKXrKYz8kJ28TZhLB/view?usp=drive_link

**Comment by Arne-W** [comment]
@AndKe For me it works :smile: 
![image](https://github.com/ArduPilot/apm_planner/assets/7621911/ed0e37d4-3836-4506-a39f-274b74ef0334)

**Comment by AndKe** [comment]
@Arne-W  - sorry to disturb you just to expose my failure to spot a git detached head situation.  :)

**Comment by Arne-W** [comment]
No Problem :smiley:
