### ISSUE TITLE
Archlinux build problems

### ISSUE THREAD

**Issue by ladecadence** [ArduPilot/apm_planner#258]
After adding the fixes proposed in issue #245, I had to comment lines 54 and 57 in src/QGC.h in order to build apm planner:
#include <cmath>
#ifndef isnan
//#define isnan(x) std::isnan(x)
#endif
#ifndef isinf
//#define isinf(x) std::isinf(x)
#endif

**Comment by felixsteghofer** [comment]
The fix described by @ladecadence is now also needed on linux arch (or on every linux?!)

**Comment by felixsteghofer** [comment]
not checked for a long time but seems fixed now on master.

**Comment by billbonney** [comment]
Thx closed :+1:
