### ISSUE TITLE
APM Planner 2 - Install Firmware - Port Locked After Pixhawk Restart

### ISSUE THREAD

**Issue by JQuesenberry** [ArduPilot/apm_planner#289]
I have installed Ubuntu 12.10 and I downloaded the repo for APM Planner and built it per the README. The program runs fine, however, when I try to "Install Firmware", I've only tried with ArduRover v2.45, it gets up to the "Please unplug, and plug back in the PX4/Pixhawk" and then things break. I unplug the USB cable and plug it back in, which results in errors in the output: "Started downloading http://firmware.diydrones.com/Rover/stable/PX4/APMrover2-v2.px4
Finished downloading /tmp/qt_temp.Sm9470
ERROR: Port ttyACM0 is locked by an external process. Run: "sudo lsof /dev/ttyACM0" to determine the associated programs. They can usually be uninstalled." Has anyone seen this? Or does anyone know how to fix it?

**Comment by Arne-W** [comment]
cannot reproduce on current ubuntu 16.04
