### ISSUE TITLE
Crash when pulling the USB cable while connected

### ISSUE THREAD

**Issue by hsteinhaus** [ArduPilot/apm_planner#298]
The following crash occurred after I pulled the USB cable while APMP was connected and idling.
OS: FC19 64bit. APMP was the latest master (2697cdb181537cf0f90bdf6397e46d6336ca4a76)

see https://gist.github.com/billbonney/02353abf55567a7298ca

**Comment by Arne-W** [comment]
should be fixed since d32aa4064dacb2cd5aad2047409e4a59cdc7cf7d.
