### ISSUE TITLE
First waypoint can't be moved down

### ISSUE THREAD

**Issue by rh-galaxy** [ArduPilot/apm_planner#335]
![first_wp_down](https://cloud.githubusercontent.com/assets/3186413/2987004/cab41aba-dc49-11e3-90a1-41bf1f99c601.jpg)

Nothing happens when the down-button is pressed for the first wp.
And the second wp can't be moved up.

Also the up-button should be disabled for the first wp, and the down-button for the last wp.

---

Now the up-down buttons for the first wp are disabled but wasn't before, don't know what i did. Anyway, more than one thing is wrong with the waypoints in the data and plan views.
![up_down_disabled](https://cloud.githubusercontent.com/assets/3186413/2987294/a11b3a46-dc4c-11e3-8a79-5b520c1026b9.jpg)

**Comment by Arne-W** [comment]
seems to be fixed - closing.
