### ISSUE TITLE
APM Planner crashes when trying to download more than one logs

### ISSUE THREAD

**Issue by cmavr8** [ArduPilot/apm_planner#357]
When I select multiple logs and try to download them all at once, APM Planner crashes. If I download each one separately it works.

APM Planner 2.0.10 (pulled yesterday from branch serialfix-wip), on Ubuntu 13.10 64 bit. Console output in next comment.

**Comment by Arne-W** [comment]
@billbonney This bug is fixed I think :smile: could be closed!

**Comment by cmavr8** [comment]
This has been too long and I am not able to test the fix. Since there are no new reports/unhappy users let's close it. Thanks!
