### ISSUE TITLE
Linux: Logfile graphing starts at line 480

### ISSUE THREAD

**Issue by sgofferj** [ArduPilot/apm_planner#565]
Version: Nightly Ubuntu 64, 31b75fc8-2.0.16-rc1-4-g31b75fc-DEV

When loading a .log-file, graph area is set up and axis labels are displayed but nothing is plotted. Tested with several different logfiles.
Also, no flight path is plotted in the map view.

**Comment by Arne-W** [comment]
could be closed - does not happen anymore

**Comment by Arne-W** [comment]
@billbonney Can be closed now....
