### ISSUE TITLE
Linux: Segfault when connecting to a non-autopilot device

### ISSUE THREAD

**Issue by sgofferj** [ArduPilot/apm_planner#567]
Version: Nightly Ubuntu 64, 31b75fc-2.0.16-rc1-4-g31b75fc-DEV

Just for testing around, I connected APP2 to an PX4 Flow at /dev/ttyACM0 which resulted into a freeze and then crash. Shouldn't it complain that the PX4 Flow isn't an autopilot?
Unfortunately, I hadn't set up debugging, so no dump available.

**Comment by nabinodd** [comment]
Similar problem but when connecting over UDP to simulated px4 vehicle.
[apmplanner2_crash.log](https://github.com/ArduPilot/apm_planner/files/6570368/apmplanner2_crash.log)

**Comment by Arne-W** [comment]
@nabinodd The version you are using is too old. Try this one:
[https://github.com/ArduPilot/apm_planner/releases/tag/2.0.28-rc1](https://github.com/ArduPilot/apm_planner/releases/tag/2.0.28-rc1)

**Comment by nabinodd** [comment]
> @nabinodd The version you are using is too old. Try this one:
> https://github.com/ArduPilot/apm_planner/releases/tag/2.0.28-rc1

Worked for me!!
