### ISSUE TITLE
Negative values in MAG graphs not represented correctly

### ISSUE THREAD

**Issue by andyp1per** [ArduPilot/apm_planner#613]
In graphs of MAG X,Y,Z values I see values of 65535 etc rather than -1 so someone is decoding a signed short incorrectly. This problem does not appear in Mission Planner 1.3.19, only APM Planner 2.0.15 (Windows and OSX). I'm sure this must be a dup, but cannot find it.

**Comment by andyp1per** [comment]
If you need a dataflash log that shows this I can provide it

**Comment by peterbarker** [comment]
Is the dataflash log file in question a text log or binary log?

If a text log - how was it produced?  Downloaded, or exported using APM Planner?

**Comment by andyp1per** [comment]
Binary, downloaded over mavlink. BTW I stopped using APM Planner for this and other reasons. I occasionally have switched back and it does not seem consistent now - I have seen good MAG graphs, but generally not.

**Comment by billbonney** [comment]
Can you post a link to a log, or email me. Thx

**Comment by andyp1per** [comment]
https://dl.dropboxusercontent.com/u/108802517/112.BIN
This came directly off the flash card

**Comment by billbonney** [comment]
Thanks, I couldn't see any values of 65535 in that log.  But that's with 2.0.18-rc2-17-xxxx see http://firmware.diydrones.com/Tools/APMPlanner/daily/2015-07-16/ 

Can you reproduce the error with the latest build?

**Comment by peterbarker** [comment]
Brain dump:

The original binary logs appear correct.  I first found this issue in an exported log, but it appears the problem is in the in-memory model - a problem on log load, as people are having problems with the graphs.

I do not believe this issue reproduces on Linux - I certainly haven't managed it!  What OS are you using, Bill?

It isn't just a boundary problem - I've seen 65530 in (exported text-format) logs.  Definitely seems to be a different-integer-length-being-used issue.

The mav* tools don't cope well with out-of-range values like this in logs.  I'm working up a patch for that.

The relevant load code in AP2DataPlotThread looks correct:
                                else if (typeCode == 'h') //int16_t
                                {
                                    qint16 val;
                                    packetstream >> val;
                                    linetoemit += "," + QString::number(val,'f',0);
                                    valuepairlist.append(QPair<QString,QVariant>(labelstrsplit.at(j),val));
                                }

... bit I think the problem has to lie in there somewhere.

**Comment by billbonney** [comment]
I tested this on Xubuntu 15.04 (but at home I run OSX 10.10) I'll test again when I get home.

The graph code was written by @malcom2073 so he knows it best. I'm not so familiar with it. it does seem like sign/unsigned conversion issue if we are seeing 65XXX values.

**Comment by billbonney** [comment]
@peterbarker the odd thing about using `QString::number(val,'f',0);` is that val is converted to a double, when you could use `QString::number(uint n, int base = 10)` function instead, for example. I'd expect a int8_t or uint8_t to convert to a uint without a problem in that call.

The loadAsciiLog treats all input as a int on line504

my exported log of 112.BIN loads with errors in 1548 lines  in the log file. which can't be good.

If we had a log with the error reported in loading of a log that would really help.

Anyway, must sleep, I'll look at it more tomorrow if I get some time,.

**Comment by andyp1per** [comment]
I'm running on Windows 7 & OSX. I do see the problem more on Windows.

**Comment by peterbarker** [comment]
@billbonney Yes, that is odd.  I must admit my eyes skipped over that line on the assumption that the problems were with the in-memory model, and that line was producing some sort of output only.  Perhaps the graph problems were only on loaded text logs?   @andyp1per - could you confirm that the bad graphs are produced when you load a binary dataflash log, please?

**Comment by andyp1per** [comment]
All the issues I see are with binary dataflash logs, but that's pretty much all I use so would struggle to prove that this works elsewhere.

**Comment by billbonney** [comment]
@andyp1per can you reproduce the problem and let's us know how and with what log, thx

I'm convinced that a an 8bit or 16 bit unsigned to double is going to be wrong conversion.  We should check other places QString::number is being used. I think the conversion to string needs to use its closest type, ie uint, ulong, etc associated function. I just had a similar effect on some other code I was working on. (Ie. Unsigned intro signed, into unsigned) I just like to be able to prove it as well.

**Comment by andyp1per** [comment]
Do you have an OSX build?

**Comment by billbonney** [comment]
Yep, OSX is my main platform for this.

**Comment by andyp1per** [comment]
I don't see it in the link you sent?

**Comment by billbonney** [comment]
Sorry, pre :coffee: . Had some now. I haven't implemented a fix yet, but if you can test with the latest here http://firmware.diydrones.com/Tools/APMPlanner/daily/2015-07-18/ and reproduce that would be awesome.

**Comment by billbonney** [comment]
this is the changes I am proposing https://github.com/diydrones/apm_planner/tree/logconversion-wip

**Comment by andyp1per** [comment]
With the latest pre-release I cannot reproduce this on Windows 7

**Comment by billbonney** [comment]
That's good to know. I'm still think the suggested changes make sense, as covering signs can get tricky when the signed numbers are bigger than -32768. You may have experienced an earlier issue for the same reason.

**Comment by Arne-W** [comment]
does not happen any more on current master
