### ISSUE TITLE
Crash After Pressing DroneShare Button

### ISSUE THREAD

**Issue by RedPhoton** [ArduPilot/apm_planner#635]
This is with APM Planner v2.0.15 on Mac. I had just downloaded a log file from a Pixhawk and proceeded to upload it to DoneShare but got the crash right after pressing the DroneShare button. I saved the Apple crash description in dropbox, see https://www.dropbox.com/l/sZqrCeDvkvIRpFYf9ZuwJs

The log file is also in dropbox, see https://www.dropbox.com/l/htYO2Miy1l1vCPvhBU2Ejq

**Comment by Arne-W** [comment]
As droneshare is not supported anymore - I will close this
