### ISSUE TITLE
Log Viewer Message Selection Scroll Glitch

### ISSUE THREAD

**Issue by labtoast** [ArduPilot/apm_planner#650]
The graph view has a bug where the message type selection view is not scrolling properly. I think the height of the viewable area is not being calculated correctly when message types are expanded. The scrolling does work correctly when no message types are expanded.

Steps to reproduce:
1. Launch apm_planner
2. Click graphs mode
3. Load log file
4. Expand a few message types
5. Arrow keys can now navigate to out of view message types.

![screen shot 2015-03-19 at 1 07 54 pm](https://cloud.githubusercontent.com/assets/8050526/6736214/dd349efc-ce39-11e4-9434-9510b9fd7467.png)
![screen shot 2015-03-19 at 1 08 07 pm](https://cloud.githubusercontent.com/assets/8050526/6736218/dd3ae3f2-ce39-11e4-8953-bd8f37f95a1b.png)
![screen shot 2015-03-19 at 1 08 13 pm](https://cloud.githubusercontent.com/assets/8050526/6736217/dd39f2bc-ce39-11e4-8244-e0731395ab6f.png)
![screen shot 2015-03-19 at 1 08 21 pm](https://cloud.githubusercontent.com/assets/8050526/6736216/dd3830bc-ce39-11e4-82d5-5ef703326219.png)
![screen shot 2015-03-19 at 1 08 28 pm](https://cloud.githubusercontent.com/assets/8050526/6736215/dd370002-ce39-11e4-9429-49a4cfa1b3e5.png)

**Comment by malcom2073** [comment]
Which version of AP2 are you running? Help->About APM Planner 2.0, the first two lines of text.

**Comment by labtoast** [comment]
From "Help->About APM Planner 2.0":
APM Planner v2.0.16
(8ff71391-2.0.16-15-g8ff7139)

From codebase:
commit 8ff71391f51eeb387839d3d0acd29bdab2cdcdf9

System:
Qt 5.3.2
OSX 10.10.2

It looks like I can scroll further off the viewable area by expanding additional message types.

**Comment by malcom2073** [comment]
Can you do a full rebuild (clean, qmake, build)? It looks like you missed some UI changes, which can happen if you don't do a fresh build after a checkout.

The telltale is the message selection dialog is now the full height of the screen, making the table view less wide. This is what it looks like now:

![image](https://cloud.githubusercontent.com/assets/1726042/6968445/ec7c4094-d934-11e4-89fd-f3994e854157.png)

**Comment by Arne-W** [comment]
seems to be fixed
