### ISSUE TITLE
Droneshare uploads not working with tlogs

### ISSUE THREAD

**Issue by zlite** [ArduPilot/apm_planner#722]
![droneshare_upload_and_apm_planner_v2_0_17__chriss-macbook-air-2_local__192_168_1_204_](https://cloud.githubusercontent.com/assets/18071/7925851/b0f1174c-087e-11e5-832e-e6fae39021d6.png)

Replicated on three logs. This same log uploads fine to Droneshare if I do it through the Droneshare web uploader.

**Comment by martinjuju** [comment]
same problem with all my logs

**Comment by Arne-W** [comment]
Asb droneshare does not exist anymore - I will close this issue
