### ISSUE TITLE
Flight Plan : strange selection/drag behavior.

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/apm_planner#831]
to reproduce:
-load mission https://gist.github.com/AndKe/dacdc5f925030bf40a6b
-try to do things in this video.  : https://youtu.be/K7BthmcUcD4

I am not sure whatever https://github.com/diydrones/apm_planner/commit/0ce96ed49c144102ea9384e649bcc1316fb0f7d2 was meant to fix/improve this - (this behaviour is nothing new)  
-video shows current master 

please observe the strange way dragging sometimes does not update any waypoint, and sometimes updates two at the same time.

**Comment by Arne-W** [comment]
will be fixed wiith #1025. As there is a duplicate for this bug #1019 which is referenced by the fix - I will close this.
