### ISSUE TITLE
APM Planner 2.0 not displaying last parameter in full parameter list

### ISSUE THREAD

**Issue by f11music** [ArduPilot/apm_planner#871]
WPNAV_SPEED_UP is only half way visible and the values are hard to see or edit. This is on Mac with APM Planner 2.0.19 rc4

**Comment by dcarpy** [comment]
For what it is worth, both Windows and Linux look good. APM Planner v2.0.19-rc4 using Qt version 5.4.2.

**Comment by ustramooner** [comment]
works fine for me too - 2.0.19

**Comment by Arne-W** [comment]
looks outdated :smiley:
