### ISSUE TITLE
Widget: Info View (Quick) poor choice of colors.

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/apm_planner#932]
Maybe something else than random would be nice?

![screenshot from 2016-04-18 09-29-26](https://cloud.githubusercontent.com/assets/1468842/14601242/6c4290a4-0561-11e6-876e-c2f156631a5c.png)

Ultimately, it would be nice to have the ability to set colors, and/or set colors based on value.

**Comment by dcarpy** [comment]
@AndKe Have you noticed by chance if the colors have been better since commit 68f292e?  Just checking before I make a similar change in AP2DataPlot2D.cpp...

**Comment by AndKe** [comment]
True, it's definitely not making crazy choices, mostly by avoiding extreme light/dark colors, but it has a tendency to end up with very similar colors, not sure how good that is for graphs.

![screenshot from 2016-05-19 22-59-19](https://cloud.githubusercontent.com/assets/1468842/15409800/b0cba40e-1e16-11e6-8e58-27079a13b538.png)


![Uploading Screenshot from 2016-05-19 22-59-45.png…]()

**Comment by dcarpy** [comment]
@AndKe Agreed.  I'm thinking maybe for both I should use the [Golden Ratio](http://martin.ankerl.com/2009/12/09/how-to-create-random-colors-programmatically/).

**Comment by AndKe** [comment]
Yes, Golden Ratio looks good, 
Looking at the examples:
![screenshot from 2016-05-20 09-04-51](https://cloud.githubusercontent.com/assets/1468842/15419951/017cc358-1e6a-11e6-9b87-b66a8997d960.png)

I see that 8 colors are chosen before the pattern repeats with less different colors.
the best solution, at least for graphs, could be to toggle between the settings every 8 colors:
like on the picture above: 
first 8 colors picked from A-H from the upper example, then next 8 colors from A-H on the lower example, then next 8 colors from upper I-P 8 and so on...
