### ISSUE TITLE
2.0.20 Accel calibration on Mac

### ISSUE THREAD

**Issue by markwbrown** [ArduPilot/apm_planner#933]
I'm getting INS not calibrated warnings. When connected, the Accel Calibration starts, but no prompts are given, just a countdown timer.  I can see [MAV 001:1] Place vehicle level and press any key.  in the info view, but keypress is not registered. Using ArduCopter board 3.2.1 with USB link. The primary flight display shows changes when I tilt the board which look accurate, but the calibration is simply not working.

**Comment by billbonney** [comment]
Support is handled here http://discuss.ardupilot.org/c/ground-control-software/apm-planner-2-0 thx
