### ISSUE TITLE
Can't calibrate accelerometer

### ISSUE THREAD

**Issue by yazinsai** [ArduPilot/apm_planner#945]
When I try to run the calibration, I get the below screen:

![image](https://cloud.githubusercontent.com/assets/1846034/15334674/4912972e-1c80-11e6-9dfa-130cc8237c92.png)

Here's the debug file:
```
DEBUG 2016-05-17T22:38:04.083 UAS::executeCommand 241 conf 0 param1 0 param2 0 param3 0 param4 0 param5 1 param6 0 param7 0 
 INFO 2016-05-17T22:38:04.203 STATUS TEXT: 6 : "Initialising APM" 
DEBUG 2016-05-17T22:38:04.204 APM: Text Message rx'd "Initialising APM" 
DEBUG 2016-05-17T22:38:06.220 Param: "INS_PRODUCT_ID" :  QVariant(int, 5) 
DEBUG 2016-05-17T22:38:06.221 Param: "INS_ACCSCAL_X" :  QVariant(double, 1) 
DEBUG 2016-05-17T22:38:06.222 Param: "INS_ACCSCAL_Y" :  QVariant(double, 1) 
DEBUG 2016-05-17T22:38:06.224 Param: "INS_ACCSCAL_Z" :  QVariant(double, 1) 
DEBUG 2016-05-17T22:38:06.225 Param: "INS_ACCOFFS_X" :  QVariant(double, 0) 
DEBUG 2016-05-17T22:38:06.226 Param: "INS_ACCOFFS_Y" :  QVariant(double, 0) 
DEBUG 2016-05-17T22:38:06.227 Param: "INS_ACCOFFS_Z" :  QVariant(double, 0) 
DEBUG 2016-05-17T22:38:06.227 Param: "INS_GYROFFS_X" :  QVariant(double, 0.00276027) 
DEBUG 2016-05-17T22:38:06.228 Param: "INS_GYROFFS_Y" :  QVariant(double, 0.0208213) 
DEBUG 2016-05-17T22:38:06.229 Param: "INS_GYROFFS_Z" :  QVariant(double, -0.00978289) 
DEBUG 2016-05-17T22:38:06.230 Param: "INS_ACC2SCAL_X" :  QVariant(double, 1) 
DEBUG 2016-05-17T22:38:06.230 Param: "INS_ACC2SCAL_Y" :  QVariant(double, 1) 
DEBUG 2016-05-17T22:38:06.231 Param: "INS_ACC2SCAL_Z" :  QVariant(double, 1) 
DEBUG 2016-05-17T22:38:06.238 Param: "INS_ACC2OFFS_X" :  QVariant(double, 0) 
DEBUG 2016-05-17T22:38:06.239 Param: "INS_ACC2OFFS_Y" :  QVariant(double, 0) 
DEBUG 2016-05-17T22:38:06.239 Param: "INS_ACC2OFFS_Z" :  QVariant(double, 0) 
DEBUG 2016-05-17T22:38:06.240 Param: "INS_GYR2OFFS_X" :  QVariant(double, -0.0271287) 
DEBUG 2016-05-17T22:38:06.241 Param: "INS_GYR2OFFS_Y" :  QVariant(double, 0.0292677) 
DEBUG 2016-05-17T22:38:06.241 Param: "INS_GYR2OFFS_Z" :  QVariant(double, -0.00599059) 
DEBUG 2016-05-17T22:38:06.242 Param: "INS_ACC3SCAL_X" :  QVariant(double, 0) 
DEBUG 2016-05-17T22:38:06.242 Param: "INS_ACC3SCAL_Y" :  QVariant(double, 0) 
DEBUG 2016-05-17T22:38:06.243 Param: "INS_ACC3SCAL_Z" :  QVariant(double, 0) 
DEBUG 2016-05-17T22:38:06.243 Param: "INS_ACC3OFFS_X" :  QVariant(double, 0) 
DEBUG 2016-05-17T22:38:06.244 Param: "INS_ACC3OFFS_Y" :  QVariant(double, 0) 
DEBUG 2016-05-17T22:38:06.244 Param: "INS_ACC3OFFS_Z" :  QVariant(double, 0) 
DEBUG 2016-05-17T22:38:06.245 Param: "INS_GYR3OFFS_X" :  QVariant(double, 0) 
DEBUG 2016-05-17T22:38:06.245 Param: "INS_GYR3OFFS_Y" :  QVariant(double, 0) 
DEBUG 2016-05-17T22:38:06.246 Param: "INS_GYR3OFFS_Z" :  QVariant(double, 0) 
DEBUG 2016-05-17T22:38:06.247 APM: Text Message rx'd "SUCCESS: Executed CMD: 241" 
DEBUG 2016-05-17T22:38:06.247 Rejecting message, check mismatch: current_state:  0  ==  3 , system id  0  ==  1 , comp id  1  ==  1 
```

Specs:
- Hardware: APM 2.8
- Software: APM Planner v2.0.20
- Firmware: Arduplane v3.5.3

**Comment by mboland** [comment]
I have had this happen at random times with different controllers.
I downloaded the latest version which seemed to fix things.

**Comment by yazinsai** [comment]
@mboland thanks for the quick response -- latest version of APM planner, or the beta firmware?

**Comment by billbonney** [comment]
![preac3 4-compatmode](https://cloud.githubusercontent.com/assets/959994/15347503/23c971a8-1c77-11e6-98bc-36b4f285e0dd.png)
You may need to make sure this option is unchecked

**Comment by yazinsai** [comment]
It's unchecked:

![image](https://cloud.githubusercontent.com/assets/1846034/15348615/4e5555f2-1cdd-11e6-9109-3fa267510b8c.png)

**Comment by danybony** [comment]
I'm having the same issue with APM 2.8 and APM Planner v2.0.23-rc1

**Comment by billbonney** [comment]
Support requests are handled here http://discuss.ardupilot.org/c/ground-control-software/apm-planner-2-0

**Comment by andrenventer** [comment]
Guys, lets fix this by making "Text Severity Compatibility" a default "TRUE"

**Comment by billbonney** [comment]
@andrenventer that's only correct if you are not running AC3.4+. The fix is to add detection of the APM FW versions and automatically select the correct remapping.

**Comment by andrenventer** [comment]
I just installed a fresh apm_planner on mac - updated a PixHawk with latest stable and the Calibration feature for Accel was broken

**Comment by yazinsai** [comment]
I ultimately managed to get it working using the CLI (`mavproxy.py`) which worked fine

**Comment by FlyingCatAlex** [comment]
In config/tuning tab, check Enable Ardupilot Text severity Compatibility Mode. Then reopen APM software. This works for me.

**Comment by billbonney** [comment]
ok, I've add a fix that will auto detect the APM version and do the correct things without doing the checkbox for AC3.4+. Please verify the build here (OSX only at the moment) or build from master.

http://firmware.ardupilot.org/Tools/APMPlanner/daily/2016-08-05/
