### ISSUE TITLE
Graph: Crash by .tlog with many mode-changes.

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/apm_planner#947]
to reproduce this crash - issue https://github.com/ArduPilot/apm_planner/issues/941 must be solved or avoided: test with fprinf() workaround or disable QLOG

crash data:
https://gist.github.com/AndKe/b8ee063bd039eafe17d4abce1f8e2464

log that causes it: (as usual , its a random log from my Download folder from some random support case)
[20160405182728.tlog.zip](https://github.com/ArduPilot/apm_planner/files/273364/20160405182728.tlog.zip)

**Comment by AndKe** [comment]
unable to reproduce when using  https://github.com/ArduPilot/apm_planner/pull/950

**Comment by billbonney** [comment]
Close, reopen if 2.0.23-rc1 has the issue
