### ISSUE TITLE
Graph: crash when try to load 5+ hours log

### ISSUE THREAD

**Issue by suraqis** [ArduPilot/apm_planner#949]
APM Planner crashes every time when opens large (over 5 hours) dataflash log file both .bin (340Mb) and .log (860Mb).

**Comment by Arne-W** [comment]
Never had such a big logfile - I'm flying multicopters :smile: - if you can zip it and send me a Link I will test and try to solve it.

**Comment by billbonney** [comment]
My suggestion is to use split ;-)

**Comment by billbonney** [comment]
this log linked in the [post](https://github.com/ArduPilot/apm_planner/issues/955#issuecomment-224703098) is 458MB and loads ok
