### ISSUE TITLE
Dockerfile for running apmplanner2 on other linux distros without compiling.

### ISSUE THREAD

**Issue by Rikbruggink** [ArduPilot/apm_planner#953]
Hi all,

I created a dockerfile for running apmplanner2 on my non ubuntu linux system. Is this something more members of the community are interested in and possible merge it under arducopter/apm_planner or an alternative repo?

With kind regards,

Rik

**Comment by billbonney** [comment]
you can make a PR against APM Planner 2.0. I'll merge it in. Thx

**Comment by billbonney** [comment]
Merged thanks. 👍
